export class apiurls {
  apiUrls = {
    getSecurityQuesstion : 'https://tqgb5ax63f.execute-api.us-east-1.amazonaws.com/development/getQuestion' ,
    verifyAnswer : 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-verifyquestion' ,
    staticContent : 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/getallstaticdata' ,
    faq : 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getfaq' ,
    editStaticContent : 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/editstaticdata' ,
    editFaq : 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/editfaq',
    deleteFaq : 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-deletedata',
    addFaq : 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/addfaq' ,
    addStorage:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-addspace',
    getStorage:' https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-spacetype',
    deleteStorage:' https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-deletespace',
    editStorage:' https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-editspacetype',
    addStorageFeatures:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-addfeaturelist',
    getStorageFeatures: 'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getstoragefeatures',
    getParticularFeatures:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getparticularfeature',
    deleteStorageFeatures:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-deletefeatures',
    editStorageFeatures:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-editstoragefeatures',
    storageStatus:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-spacestatus',
    addAccessiblity:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-addaccessiblity',
    getAccessiblity:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getaccessiblity',
    deleteAccessiblity:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-deleteaccessiblity',
    addBanner:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-addbanner',
    getBanner:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getbanner',
    deleteBanner:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-bannerdelete',
    editBanner:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-editbanner',
    addBlog:' https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-addblog',
    deleteBlog:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-deleteblog',
    editBlog:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-editblog',
    getBlog:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getblog',
    addStoringPlan:' https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-storingplan',
    getStoringPlan:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getsstoringplan',
    editStoringPlan:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-editstoringplan',
    deleteStoringPlan:' https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-deletestoringplan',
    addFeeManagement:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-addfeemanagement',
    getFeeManagement:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getfee',
    editFeeManagement:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-feeedit',
    admincityprice:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-admincityprice',
    editadminCity:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-editadminstorage',
    deleteadminCity:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-deleteadmincity',
    getAdminCitys:'https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getadmincities'
  };
}
// https://tu4r0ygyt7.execute-api.us-east-1.amazonaws.com/P2P/p2p-getstoragefeatures